default: &default
  adapter: postgresql
  encoding: unicode

  # host: postgres_container
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>

development:
  <<: *default

production:
  <<: *default