services:
  db:
    image: postgres:17
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: rails_container
    env_file:
      - ./backend/.env.development  # Backend specific env file
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend  # volumes:

  frontend:
    build:
      context: ./frontend
    container_name: vite_frontend
    ports:
      - "5173:5173"  # Vite's default port
    depends_on:
      - backend
    volumes:
      - ./frontend:/app:rw
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      VITE_API_URL: ${VITE_API_URL}
    command: npm run dev

